import type { AuthMethod } from '../auth';
import type { ProviderConfig, ModelConfig } from '../types';
import type { WellKnownAuthPresetId } from './auths';
import {
  WellKnownModelId,
  WELL_KNOWN_MODELS,
  getAlternativeIds,
  normalizeWellKnownConfigs,
} from './models';

export type WellKnownProviderConfig = Omit<
  ProviderConfig,
  'auth' | 'models'
> & {
  /**
   * Category label used for grouping in UI (QuickPick separators).
   * Stored as an i18n key (passed through `t()` by the UI).
   */
  category: string;
  authTypes?: WellKnownAuthTypeId[];
  models: WellKnownModelId[];
};

export type WellKnownAuthTypeId = AuthMethod | WellKnownAuthPresetId;

export const WELL_KNOWN_PROVIDERS: WellKnownProviderConfig[] = [
  {
    name: 'Open AI',
    category: 'General',
    type: 'openai-responses',
    baseUrl: 'https://api.openai.com',
    authTypes: ['api-key'],
    models: [
      'gpt-5.4',
      'gpt-5.4-mini',
      'gpt-5.4-nano',
      'gpt-5.4-pro',
      'gpt-4.1',
      'gpt-oss-120b',
      'gpt-oss-20b',
    ],
  },
  {
    name: 'Google AI Studio',
    category: 'General',
    type: 'google-ai-studio',
    baseUrl: 'https://generativelanguage.googleapis.com',
    authTypes: ['api-key'],
    models: [
      'gemini-3.1-pro-preview',
      'gemini-3-pro-preview',
      'gemini-3-flash-preview',
      'gemini-2.5-pro',
      'gemini-2.5-flash',
      'gemini-2.5-flash-lite',
      'gemini-2.0-flash',
      'gemini-2.0-flash-lite',
    ],
  },
  {
    name: 'Google Vertex AI',
    category: 'General',
    type: 'google-vertex-ai',
    baseUrl: 'https://aiplatform.googleapis.com',
    authTypes: ['google-vertex-ai-auth'],
    models: [
      'gemini-3.1-pro-preview',
      'gemini-3-pro-preview',
      'gemini-3-flash-preview',
      'gemini-2.5-pro',
      'gemini-2.5-flash',
      'gemini-2.5-flash-lite',
      'gemini-2.0-flash',
      'gemini-2.0-flash-lite',
    ],
  },
  {
    name: 'Anthropic',
    category: 'General',
    type: 'anthropic',
    baseUrl: 'https://api.anthropic.com',
    authTypes: ['api-key'],
    models: [
      'claude-opus-4-7',
      'claude-opus-4-6',
      'claude-opus-4-5',
      'claude-sonnet-4-5',
      'claude-haiku-4-5',
    ],
  },
  {
    name: 'xAI',
    category: 'General',
    type: 'openai-responses',
    baseUrl: 'https://api.x.ai',
    authTypes: ['api-key'],
    models: [
      'grok-4.20-0309-reasoning',
      'grok-4.20-0309-non-reasoning',
      'grok-4',
      'grok-4-1-fast-reasoning',
      'grok-4-1-fast-non-reasoning',
      'grok-code-fast-1',
    ],
  },
  {
    name: 'Hugging Face (Inference Providers)',
    category: 'General',
    type: 'openai-chat-completion',
    baseUrl: 'https://router.huggingface.co/v1',
    authTypes: ['api-key'],
    models: [],
  },
  {
    name: 'OpenRouter',
    category: 'General',
    type: 'openai-chat-completion',
    baseUrl: 'https://openrouter.ai/api/v1',
    balanceProvider: { method: 'openrouter' },
    authTypes: ['api-key'],
    models: [],
  },
  {
    name: 'Synthetic',
    category: 'General',
    type: 'openai-chat-completion',
    baseUrl: 'https://api.synthetic.new/openai/v1',
    balanceProvider: { method: 'synthetic' },
    authTypes: ['api-key'],
    models: [
      'MiniMax-M2.5',
      'qwen3.5-397b-a17b',
      'kimi-k2.5',
      'glm-4.7',
      'deepseek-r1-0528',
      'deepseek-v3-0324',
      'deepseek-v3.2',
      'llama-3.3-70b',
      'MiniMax-M2.1',
      'kimi-k2-0905-preview',
      'kimi-k2-thinking',
      'gpt-oss-120b',
      'deepseek-v3',
      'qwen3-235b-a22b-thinking-2507',
      'qwen3-coder-480b-a35b-instruct',
    ],
  },
  {
    name: 'AIHubMix',
    category: 'General',
    type: 'openai-chat-completion',
    baseUrl: 'https://aihubmix.com/v1',
    balanceProvider: { method: 'aihubmix' },
    authTypes: ['api-key'],
    models: [],
  },
  {
    name: 'Cerebras',
    category: 'General',
    type: 'openai-chat-completion',
    baseUrl: 'https://api.cerebras.ai',
    authTypes: ['api-key'],
    extraBody: {
      reasoning_format: 'parsed',
    },
    models: [
      'llama3.1-8b',
      'llama-3.3-70b',
      'gpt-oss-120b',
      'qwen-3-32b',
      'qwen-3-235b-a22b-instruct-2507',
      'zai-glm-4.7',
    ],
  },
  {
    name: 'OpenCode Zen (OpenAI Chat Completion)',
    category: 'General',
    type: 'openai-chat-completion',
    baseUrl: 'https://opencode.ai/zen',
    authTypes: ['api-key'],
    models: ['big-pickle', 'glm-4.7-free', 'kimi-k2.5-free'],
  },
  {
    name: 'OpenCode Zen (OpenAI Responses)',
    category: 'General',
    type: 'openai-responses',
    baseUrl: 'https://opencode.ai/zen',
    authTypes: ['api-key'],
    models: ['gpt-5-nano'],
  },
  {
    name: 'OpenCode Zen (Anthropic Messages)',
    category: 'General',
    type: 'anthropic',
    baseUrl: 'https://opencode.ai/zen',
    authTypes: ['api-key'],
    models: ['minimax-m2.1-free'],
  },
  {
    name: 'OpenCode Zen (Gemini)',
    category: 'General',
    type: 'google-ai-studio',
    baseUrl: 'https://opencode.ai/zen',
    authTypes: ['api-key'],
    models: ['gemini-3-pro', 'gemini-3-flash'],
  },
  {
    name: 'OpenCode Go (OpenAI Chat Completion)',
    category: 'General',
    type: 'openai-chat-completion',
    baseUrl: 'https://opencode.ai/zen/go/v1',
    authTypes: ['api-key'],
    models: [
      'glm-5.1',
      'glm-5',
      'kimi-k2.5',
      'kimi-k2.6',
      'deepseek-v4-pro',
      'deepseek-v4-flash',
      'mimo-v2-pro',
      'mimo-v2-omni',
      'mimo-v2.5-pro',
      'mimo-v2.5',
      'qwen3.6-plus',
      'qwen3.5-plus',
    ],
  },
  {
    name: 'OpenCode Go (Anthropic Messages)',
    category: 'General',
    type: 'anthropic',
    baseUrl: 'https://opencode.ai/zen/go/v1',
    authTypes: ['api-key'],
    models: ['MiniMax-M2.7', 'MiniMax-M2.5'],
  },
  {
    name: 'Nvidia',
    category: 'General',
    type: 'openai-chat-completion',
    baseUrl: 'https://integrate.api.nvidia.com',
    authTypes: ['api-key'],
    models: [],
  },
  {
    name: 'Alibaba Cloud Model Studio (China)',
    category: 'General',
    type: 'openai-chat-completion',
    baseUrl: 'https://dashscope.aliyuncs.com/compatible-mode/v1',
    authTypes: ['api-key'],
    models: [
      'qwen3-max-2026-01-23',
      'qwen3.6-plus',
      'qwen3.5-flash',
      'qwen3-coder-plus',
      'qwen3-coder-flash',
    ],
  },
  {
    name: 'Alibaba Cloud Model Studio (Coding Plan)',
    category: 'General',
    type: 'anthropic',
    baseUrl: 'https://coding.dashscope.aliyuncs.com/apps/anthropic',
    authTypes: ['api-key'],
    models: [
      'qwen3.5-plus',
      'qwen3-max-2026-01-23',
      'qwen3-coder-next',
      'qwen3-coder-plus',
      'glm-5',
      'glm-4.7',
      'MiniMax-M2.5',
      'kimi-k2.5',
    ],
  },
  {
    name: 'Alibaba Cloud Model Studio (Coding Plan - International)',
    category: 'General',
    type: 'anthropic',
    baseUrl: 'https://coding-intl.dashscope.aliyuncs.com/apps/anthropic',
    authTypes: ['api-key'],
    models: [
      'qwen3.5-plus',
      'qwen3-max-2026-01-23',
      'qwen3-coder-next',
      'qwen3-coder-plus',
      'glm-5',
      'glm-4.7',
      'MiniMax-M2.5',
      'kimi-k2.5',
    ],
  },
  {
    name: 'Alibaba Cloud Model Studio (International)',
    category: 'General',
    type: 'openai-chat-completion',
    baseUrl: 'https://dashscope-intl.aliyuncs.com/compatible-mode/v1',
    authTypes: ['api-key'],
    models: [
      'qwen3-max-2026-01-23',
      'qwen3.6-plus',
      'qwen3.5-flash',
      'qwen3-coder-plus',
      'qwen3-coder-flash',
    ],
  },
  {
    name: 'Model Scope (API-Inference)',
    category: 'General',
    type: 'openai-chat-completion',
    baseUrl: 'https://api-inference.modelscope.cn/v1',
    authTypes: ['api-key'],
    models: [],
  },
  {
    name: 'Baidu Qianfan',
    category: 'General',
    type: 'openai-chat-completion',
    baseUrl: 'https://qianfan.baidubce.com/v2',
    authTypes: ['api-key'],
    models: [
      'ernie-5.0',
      'ernie-5.0-thinking-preview',
      'ernie-4.5-turbo-128k',
      'ernie-4.5-turbo-vl',
      'ernie-4.5-turbo-vl-preview',
      'ernie-4.5-turbo-vl-32k-preview',
      'ernie-4.5-vl-28b-a3b',
      'ernie-speed-pro-128k',
      'ernie-lite-pro-128k',
      'qianfan-lightning-128b-a19b',
    ],
  },
  {
    name: 'Baidu Qianfan (Coding Plan)',
    category: 'General',
    type: 'openai-chat-completion',
    baseUrl: 'https://qianfan.baidubce.com/v2/coding',
    authTypes: ['api-key'],
    models: ['kimi-k2.5', 'deepseek-v3.2', 'glm-5', 'MiniMax-M2.5'],
  },
  {
    name: 'Cline Bot',
    category: 'General',
    type: 'openai-chat-completion',
    baseUrl: 'https://api.cline.bot/api/v1',
    authTypes: ['api-key'],
    models: [
      'claude-sonnet-4-6',
      'claude-opus-4-6',
      'gpt-5.3-codex',
      'gemini-3.1-pro-preview',
      'gemini-3-flash-preview',
      'gemini-3.1-flash-lite-preview',
      'MiniMax-M2.5',
      'MiniMax-M2.7',
      'kat-coder-pro-v1',
      'glm-5',
    ],
  },
  {
    name: 'Volcano Engine',
    category: 'General',
    type: 'openai-responses',
    baseUrl: 'https://ark.cn-beijing.volces.com/api/v3',
    authTypes: ['api-key'],
    models: [
      'doubao-seed-2-0-pro-260215',
      'doubao-seed-2-0-lite-260215',
      'doubao-seed-2-0-mini-260215',
      'doubao-seed-2-0-code-preview-260215',
    ],
  },
  {
    name: 'Volcano Engine (Coding Plan)',
    category: 'General',
    type: 'openai-chat-completion',
    baseUrl: 'https://ark.cn-beijing.volces.com/api/coding/v3',
    authTypes: ['api-key'],
    models: [
      'ark-code-latest',
      'doubao-seed-2.0-code',
      'doubao-seed-code',
      'glm-4.7',
      'deepseek-v3.2',
      'kimi-k2-thinking',
      'kimi-k2.5',
    ],
  },
  {
    name: 'Byte Plus',
    category: 'General',
    type: 'openai-responses',
    baseUrl: 'https://ark.ap-southeast.bytepluses.com/api/v3',
    authTypes: ['api-key'],
    models: [
      'doubao-seed-2-0-pro-260215',
      'doubao-seed-2-0-lite-260215',
      'doubao-seed-2-0-mini-260215',
      'doubao-seed-2-0-code-preview-260215',
    ],
  },
  {
    name: 'Tencent Cloud (China)',
    category: 'General',
    type: 'openai-chat-completion',
    baseUrl: 'https://api.hunyuan.cloud.tencent.com/v1',
    authTypes: ['api-key'],
    models: [
      'hunyuan-2.0-thinking-20251109',
      'hunyuan-2.0-instruct-20251111',
      'hunyuan-vision-1.5-instruct',
    ],
  },
  {
    name: 'DeepSeek',
    category: 'General',
    type: 'openai-chat-completion',
    baseUrl: 'https://api.deepseek.com',
    balanceProvider: { method: 'deepseek' },
    authTypes: ['api-key'],
    models: ['deepseek-v4-flash', 'deepseek-v4-pro'],
  },
  {
    name: 'Gitee AI',
    category: 'General',
    type: 'openai-chat-completion',
    baseUrl: 'https://ai.gitee.com/v1',
    authTypes: ['api-key'],
    models: [],
  },
  {
    name: 'Xiaomi MIMO',
    category: 'General',
    type: 'openai-chat-completion',
    baseUrl: 'https://api.xiaomimimo.com/v1',
    authTypes: ['api-key'],
    models: ['mimo-v2.5-pro', 'mimo-v2.5'],
  },
  {
    name: 'Xiaomi MIMO (China, Token Plan)',
    category: 'General',
    type: 'openai-chat-completion',
    baseUrl: 'https://token-plan-cn.xiaomimimo.com/v1',
    authTypes: ['api-key'],
    models: ['mimo-v2.5-pro', 'mimo-v2.5'],
  },
  {
    name: 'Xiaomi MIMO (Singapore, Token Plan)',
    category: 'General',
    type: 'openai-chat-completion',
    baseUrl: 'https://token-plan-sgp.xiaomimimo.com/v1',
    authTypes: ['api-key'],
    models: ['mimo-v2.5-pro', 'mimo-v2.5'],
  },
  {
    name: 'Xiaomi MIMO (Europe, Token Plan)',
    category: 'General',
    type: 'openai-chat-completion',
    baseUrl: 'https://token-plan-ams.xiaomimimo.com/v1',
    authTypes: ['api-key'],
    models: ['mimo-v2.5-pro', 'mimo-v2.5'],
  },
  {
    name: 'StepFun (China)',
    category: 'General',
    type: 'openai-chat-completion',
    baseUrl: 'https://api.stepfun.com/v1',
    authTypes: ['api-key'],
    models: ['step-3.5-flash', 'step-2-mini', 'step-1o-turbo-vision'],
  },
  {
    name: 'StepFun (International)',
    category: 'General',
    type: 'openai-chat-completion',
    baseUrl: 'https://api.stepfun.ai/v1',
    authTypes: ['api-key'],
    models: ['step-3.5-flash', 'step-2-mini', 'step-1o-turbo-vision'],
  },
  {
    name: 'Ollama Local',
    category: 'General',
    type: 'ollama',
    baseUrl: 'http://localhost:11434/api',
    authTypes: ['none'],
    models: [],
    autoFetchOfficialModels: true,
  },
  {
    name: 'Ollama Cloud',
    category: 'General',
    type: 'ollama',
    baseUrl: 'https://ollama.com/api',
    authTypes: ['api-key'],
    models: [],
  },
  {
    name: 'ZhiPu AI',
    category: 'General',
    type: 'openai-chat-completion',
    baseUrl: 'https://open.bigmodel.cn/api/paas/v4',
    authTypes: ['api-key'],
    models: [
      'glm-5.1',
      'glm-5v-turbo',
      'glm-5-turbo',
      'glm-4.7',
      'glm-4.6v',
      'glm-4.7-flashx',
      'glm-4.7-flash',
      'codegeex-4',
    ],
  },
  {
    name: 'ZhiPu AI (Coding Plan)',
    category: 'General',
    type: 'openai-chat-completion',
    baseUrl: 'https://open.bigmodel.cn/api/coding/paas/v4',
    authTypes: ['api-key'],
    models: [
      'glm-5.1',
      'glm-5v-turbo',
      'glm-5-turbo',
      'glm-4.7',
      'glm-4.6',
      'glm-4.7-flashx',
      'glm-4.7-flash',
    ],
  },
  {
    name: 'Z.AI',
    category: 'General',
    type: 'openai-chat-completion',
    baseUrl: 'https://api.z.ai/api/paas/v4',
    authTypes: ['api-key'],
    models: [
      'glm-5.1',
      'glm-5v-turbo',
      'glm-5-turbo',
      'glm-4.7',
      'glm-4.6v',
      'glm-4.7-flashx',
      'glm-4.7-flash',
      'codegeex-4',
    ],
  },
  {
    name: 'Z.AI (Coding Plan)',
    category: 'General',
    type: 'openai-chat-completion',
    baseUrl: 'https://api.z.ai/api/coding/paas/v4',
    authTypes: ['api-key'],
    models: [
      'glm-5.1',
      'glm-5v-turbo',
      'glm-5-turbo',
      'glm-4.7',
      'glm-4.6',
      'glm-4.7-flashx',
      'glm-4.7-flash',
    ],
  },
  {
    name: 'MiniMax (China)',
    category: 'General',
    type: 'anthropic',
    baseUrl: 'https://api.minimaxi.com/anthropic',
    balanceProvider: { method: 'minimax' },
    authTypes: ['api-key'],
    models: ['MiniMax-M2.7', 'MiniMax-M2.7-highspeed'],
  },
  {
    name: 'MiniMax (International)',
    category: 'General',
    type: 'anthropic',
    baseUrl: 'https://api.minimax.io/anthropic',
    balanceProvider: { method: 'minimax' },
    authTypes: ['api-key'],
    models: ['MiniMax-M2.7', 'MiniMax-M2.7-highspeed'],
  },
  {
    name: 'LongCat',
    category: 'General',
    type: 'openai-chat-completion',
    baseUrl: 'https://api.longcat.chat/openai',
    authTypes: ['api-key'],
    models: [
      'LongCat-Flash-Chat',
      'LongCat-Flash-Thinking',
      'LongCat-Flash-Thinking-2601',
      'LongCat-Flash-Lite',
    ],
  },
  {
    name: 'Moonshot AI (China)',
    category: 'General',
    type: 'openai-chat-completion',
    baseUrl: 'https://api.moonshot.cn',
    balanceProvider: { method: 'moonshot-ai' },
    authTypes: ['api-key'],
    models: ['kimi-k2.6', 'kimi-k2.5'],
  },
  {
    name: 'Moonshot AI (International)',
    category: 'General',
    type: 'openai-chat-completion',
    baseUrl: 'https://api.moonshot.ai',
    balanceProvider: { method: 'moonshot-ai' },
    authTypes: ['api-key'],
    models: ['kimi-k2.6', 'kimi-k2.5'],
  },
  {
    name: 'Moonshot AI (Coding Plan)',
    category: 'General',
    type: 'anthropic',
    baseUrl: 'https://api.kimi.com/coding',
    balanceProvider: { method: 'kimi-code' },
    authTypes: ['api-key'],
    models: ['kimi-for-coding'],
  },
  {
    name: 'SiliconFlow (China)',
    category: 'General',
    type: 'openai-chat-completion',
    baseUrl: 'https://api.siliconflow.cn/v1',
    balanceProvider: { method: 'siliconflow' },
    authTypes: ['api-key'],
    models: [],
  },
  {
    name: 'SiliconFlow (International)',
    category: 'General',
    type: 'openai-chat-completion',
    baseUrl: 'https://api.siliconflow.com/v1',
    balanceProvider: { method: 'siliconflow' },
    authTypes: ['api-key'],
    models: [],
  },
  {
    name: 'StreamLake Vanchin (China)',
    category: 'General',
    type: 'openai-chat-completion',
    baseUrl: 'https://wanqing.streamlakeapi.com/api/gateway/v1/endpoints',
    authTypes: ['api-key'],
    models: [
      'kat-coder-pro-v2',
      'kat-coder-pro-v1',
      'kat-coder-exp-72b-1010',
      'kat-coder-air-v1',
    ],
  },
  {
    name: 'StreamLake Vanchin (China, Coding Plan)',
    category: 'General',
    type: 'anthropic',
    baseUrl:
      'https://wanqing.streamlakeapi.com/api/gateway/coding/kat-coder-pro-v1/claude-code-proxy',
    authTypes: ['api-key'],
    models: ['kat-coder-pro-v2', 'kat-coder-pro-v1'],
  },
  {
    name: 'StreamLake Vanchin (International)',
    category: 'General',
    type: 'openai-chat-completion',
    baseUrl: 'https://vanchin.streamlake.ai/api/gateway/v1/endpoints',
    authTypes: ['api-key'],
    models: [
      'kat-coder-pro-v2',
      'kat-coder-pro-v1',
      'kat-coder-exp-72b-1010',
      'kat-coder-air-v1',
    ],
  },
  {
    name: 'StreamLake Vanchin (International, Coding Plan)',
    category: 'General',
    type: 'anthropic',
    baseUrl:
      'https://vanchin.streamlake.ai/api/gateway/coding/kat-coder-pro-v1/claude-code-proxy',
    authTypes: ['api-key'],
    models: ['kat-coder-pro-v2', 'kat-coder-pro-v1'],
  },
  {
    name: 'OpenAI Codex (ChatGPT Plus/Pro)',
    category: 'Experimental',
    type: 'openai-codex',
    baseUrl: 'https://chatgpt.com/backend-api/codex/responses',
    balanceProvider: { method: 'codex' },
    authTypes: ['api-key', 'openai-codex'],
    models: [],
    autoFetchOfficialModels: true,
  },
  {
    name: 'GitHub Copilot',
    category: 'Experimental',
    type: 'github-copilot',
    baseUrl: 'https://api.githubcopilot.com',
    authTypes: ['github-copilot'],
    models: [],
    autoFetchOfficialModels: true,
  },
  {
    name: 'Google Antigravity',
    category: 'Experimental',
    type: 'google-antigravity',
    baseUrl: 'https://daily-cloudcode-pa.sandbox.googleapis.com',
    balanceProvider: { method: 'antigravity' },
    authTypes: ['antigravity-oauth'],
    models: [],
    autoFetchOfficialModels: true,
  },
  {
    name: 'Google Gemini CLI',
    category: 'Experimental',
    type: 'google-gemini-cli',
    baseUrl: 'https://cloudcode-pa.googleapis.com',
    balanceProvider: { method: 'gemini-cli' },
    authTypes: ['google-gemini-oauth'],
    models: [],
    autoFetchOfficialModels: true,
  },
  {
    name: 'Claude Code',
    category: 'Experimental',
    type: 'claude-code',
    baseUrl: 'https://api.anthropic.com',
    authTypes: ['api-key', 'claude-code'],
    models: [
      'claude-opus-4-7',
      'claude-opus-4-6',
      'claude-sonnet-4-6',
      'claude-opus-4-5',
      'claude-sonnet-4-5',
      'claude-haiku-4-5',
    ],
  },
  {
    name: 'Kilo Code',
    category: 'General',
    type: 'openai-chat-completion',
    baseUrl: 'https://api.kilo.ai/api/gateway',
    authTypes: ['api-key'],
    models: [],
  },
];

export function resolveProviderModels(
  provider: WellKnownProviderConfig,
): ModelConfig[] {
  const idSet = new Set<string>(provider.models);
  const declaredIds = new Map<string, string>();

  const matched = WELL_KNOWN_MODELS.filter((m) => {
    if (idSet.has(m.id)) {
      return true;
    }
    const alternativeIds = getAlternativeIds(m);
    const matchedAltId = alternativeIds.find((altId) => idSet.has(altId));
    if (matchedAltId) {
      declaredIds.set(m.id, matchedAltId);
      return true;
    }
    return false;
  });

  const providerForMatching: ProviderConfig = {
    type: provider.type,
    name: provider.name,
    baseUrl: provider.baseUrl,
    models: [],
    balanceProvider: provider.balanceProvider,
    extraHeaders: provider.extraHeaders,
    extraBody: provider.extraBody,
    timeout: provider.timeout,
    autoFetchOfficialModels: provider.autoFetchOfficialModels,
  };

  return normalizeWellKnownConfigs(matched, declaredIds, providerForMatching);
}
